/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as StickyNotesRouteImport } from './routes/sticky-notes'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as StickyNotesIndexRouteImport } from './routes/sticky-notes.index'
import { Route as StickyNotesNewRouteImport } from './routes/sticky-notes.new'
import { Route as BlogWriteIndexRouteImport } from './routes/blog.write.index'
import { Route as BlogWriteIdRouteImport } from './routes/blog.write.$id'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const StickyNotesRoute = StickyNotesRouteImport.update({
  id: '/sticky-notes',
  path: '/sticky-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StickyNotesIndexRoute = StickyNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StickyNotesRoute,
} as any)
const StickyNotesNewRoute = StickyNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StickyNotesRoute,
} as any)
const BlogWriteIndexRoute = BlogWriteIndexRouteImport.update({
  id: '/blog/write/',
  path: '/blog/write/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWriteIdRoute = BlogWriteIdRouteImport.update({
  id: '/blog/write/$id',
  path: '/blog/write/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/sticky-notes': typeof StickyNotesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/sticky-notes/new': typeof StickyNotesNewRoute
  '/blog/': typeof BlogIndexRoute
  '/sticky-notes/': typeof StickyNotesIndexRoute
  '/blog/write/$id': typeof BlogWriteIdRoute
  '/blog/write/': typeof BlogWriteIndexRoute
}
export interface FileRoutesByTo {
  '/blog/$slug': typeof BlogSlugRoute
  '/sticky-notes/new': typeof StickyNotesNewRoute
  '/': typeof ShellIndexRoute
  '/blog': typeof BlogIndexRoute
  '/sticky-notes': typeof StickyNotesIndexRoute
  '/blog/write/$id': typeof BlogWriteIdRoute
  '/blog/write': typeof BlogWriteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/sticky-notes': typeof StickyNotesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/sticky-notes/new': typeof StickyNotesNewRoute
  '/_shell/': typeof ShellIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/sticky-notes/': typeof StickyNotesIndexRoute
  '/blog/write/$id': typeof BlogWriteIdRoute
  '/blog/write/': typeof BlogWriteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sticky-notes'
    | '/blog/$slug'
    | '/sticky-notes/new'
    | '/blog/'
    | '/sticky-notes/'
    | '/blog/write/$id'
    | '/blog/write/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blog/$slug'
    | '/sticky-notes/new'
    | '/'
    | '/blog'
    | '/sticky-notes'
    | '/blog/write/$id'
    | '/blog/write'
  id:
    | '__root__'
    | '/_shell'
    | '/sticky-notes'
    | '/blog/$slug'
    | '/sticky-notes/new'
    | '/_shell/'
    | '/blog/'
    | '/sticky-notes/'
    | '/blog/write/$id'
    | '/blog/write/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  StickyNotesRoute: typeof StickyNotesRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogWriteIdRoute: typeof BlogWriteIdRoute
  BlogWriteIndexRoute: typeof BlogWriteIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sticky-notes': {
      id: '/sticky-notes'
      path: '/sticky-notes'
      fullPath: '/sticky-notes'
      preLoaderRoute: typeof StickyNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sticky-notes/': {
      id: '/sticky-notes/'
      path: '/'
      fullPath: '/sticky-notes/'
      preLoaderRoute: typeof StickyNotesIndexRouteImport
      parentRoute: typeof StickyNotesRoute
    }
    '/sticky-notes/new': {
      id: '/sticky-notes/new'
      path: '/new'
      fullPath: '/sticky-notes/new'
      preLoaderRoute: typeof StickyNotesNewRouteImport
      parentRoute: typeof StickyNotesRoute
    }
    '/blog/write/': {
      id: '/blog/write/'
      path: '/blog/write'
      fullPath: '/blog/write/'
      preLoaderRoute: typeof BlogWriteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/write/$id': {
      id: '/blog/write/$id'
      path: '/blog/write/$id'
      fullPath: '/blog/write/$id'
      preLoaderRoute: typeof BlogWriteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface StickyNotesRouteChildren {
  StickyNotesNewRoute: typeof StickyNotesNewRoute
  StickyNotesIndexRoute: typeof StickyNotesIndexRoute
}

const StickyNotesRouteChildren: StickyNotesRouteChildren = {
  StickyNotesNewRoute: StickyNotesNewRoute,
  StickyNotesIndexRoute: StickyNotesIndexRoute,
}

const StickyNotesRouteWithChildren = StickyNotesRoute._addFileChildren(
  StickyNotesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  StickyNotesRoute: StickyNotesRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogWriteIdRoute: BlogWriteIdRoute,
  BlogWriteIndexRoute: BlogWriteIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
