/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as StickyNotesRouteImport } from './routes/sticky-notes'
import { Route as ShellIndexRouteImport } from './routes/_shell.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as StickyNotesIndexRouteImport } from './routes/sticky-notes.index'
import { Route as StickyNotesNewRouteImport } from './routes/sticky-notes.new'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const StickyNotesRoute = StickyNotesRouteImport.update({
  id: '/sticky-notes',
  path: '/sticky-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const StickyNotesIndexRoute = StickyNotesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StickyNotesRoute,
} as any)
const StickyNotesNewRoute = StickyNotesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StickyNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/sticky-notes': typeof StickyNotesRouteWithChildren
  '/sticky-notes/new': typeof StickyNotesNewRoute
  '/blog/': typeof BlogIndexRoute
  '/sticky-notes/': typeof StickyNotesIndexRoute
}
export interface FileRoutesByTo {
  '/sticky-notes/new': typeof StickyNotesNewRoute
  '/': typeof ShellIndexRoute
  '/blog': typeof BlogIndexRoute
  '/sticky-notes': typeof StickyNotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/sticky-notes': typeof StickyNotesRouteWithChildren
  '/sticky-notes/new': typeof StickyNotesNewRoute
  '/_shell/': typeof ShellIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/sticky-notes/': typeof StickyNotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/sticky-notes'
    | '/sticky-notes/new'
    | '/blog/'
    | '/sticky-notes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sticky-notes/new' | '/' | '/blog' | '/sticky-notes'
  id:
    | '__root__'
    | '/_shell'
    | '/blog'
    | '/sticky-notes'
    | '/sticky-notes/new'
    | '/_shell/'
    | '/blog/'
    | '/sticky-notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  StickyNotesRoute: typeof StickyNotesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sticky-notes': {
      id: '/sticky-notes'
      path: '/sticky-notes'
      fullPath: '/sticky-notes'
      preLoaderRoute: typeof StickyNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/sticky-notes/': {
      id: '/sticky-notes/'
      path: '/'
      fullPath: '/sticky-notes/'
      preLoaderRoute: typeof StickyNotesIndexRouteImport
      parentRoute: typeof StickyNotesRoute
    }
    '/sticky-notes/new': {
      id: '/sticky-notes/new'
      path: '/new'
      fullPath: '/sticky-notes/new'
      preLoaderRoute: typeof StickyNotesNewRouteImport
      parentRoute: typeof StickyNotesRoute
    }
  }
}

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface BlogRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface StickyNotesRouteChildren {
  StickyNotesNewRoute: typeof StickyNotesNewRoute
  StickyNotesIndexRoute: typeof StickyNotesIndexRoute
}

const StickyNotesRouteChildren: StickyNotesRouteChildren = {
  StickyNotesNewRoute: StickyNotesNewRoute,
  StickyNotesIndexRoute: StickyNotesIndexRoute,
}

const StickyNotesRouteWithChildren = StickyNotesRoute._addFileChildren(
  StickyNotesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  StickyNotesRoute: StickyNotesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
